# Set our package version
environment:
  package_version: '1.0.0'
  package_suffix: '-alpha1'

image: Visual Studio 2017

# Installed nughet 4.3 to support .Net Standard 2.0 and .Net Core 2.0
install:
 - cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe

# Restore NuGet packages
before_build:
  - cmd: nuget restore

build:
  verbosity: minimal

# Unit tests in .Net Core don't behave as well 
test: off

configuration: Debug

for:
  # Development
  - branches:
      only: 
        - master

    skip_commits:
      files:
       - /*.md
       - /*.yml

    version: '$(package_version)-pre{build}-{branch}'

    # Patch package version to all match
    dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: '$(package_version).{build}'
      package_version: '$(package_version)$(package_suffix)-pre{build}'

    build:
      publish_nuget: true
      publish_nuget_symbols: true

    # Deploy to MyGet
    deploy:
      - provider: NuGet
        server: https://www.myget.org/F/oicnet/api/v2/package
        api_key:
          secure: gXj5iu2gWjqUfY5EbDi7pG7w6x3CNtWpG5p4Qy4KuWZ1rVXAzmVWXz6MIrmAUDeA
        symbol_server: https://www.myget.org/F/oicnet/symbols/api/v2/package
  
  # Releases
  - branches:
      only: 
        - releases
    
    version: '$(package_version).{build}$(package_suffix)-{branch}'
    configuration: Release

    # Patch package version to all match
    dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: '$(package_version).{build}'
      package_version: '$(package_version)$(package_suffix)'

    build:
      publish_nuget: true
      publish_nuget_symbols: true

    # Deploy to NuGet
    deploy:
      - provider: NuGet
        api_key:
          secure: UCjrAYYDUxNW2lKDcDQ5ySo4YnD1TmgiQwiyHDsFkKMlqopx82C40xUWst9Ai18G